import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Transaction, formatCurrency, formatDate } from "./finance";

const download = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
};

const csvEscape = (v: string) => {
  if (/[",\n]/.test(v)) return `"${v.replace(/"/g, '""')}"`;
  return v;
};

export function exportCSV(items: Transaction[], filename = "khaata-transactions.csv") {
  const headers = ["Date", "Type", "Category", "Merchant", "Note", "Amount (INR)", "Due Date"];
  const rows = items.map(t => [
    formatDate(t.date),
    t.type,
    t.category,
    t.merchant ?? "",
    t.note,
    t.amount.toFixed(2),
    formatDate(t.dueDate),
  ]);
  const csv = [headers, ...rows].map(r => r.map(c => csvEscape(String(c))).join(",")).join("\n");
  download(new Blob([csv], { type: "text/csv;charset=utf-8;" }), filename);
}

// Brand palette — kept in sync with index.css (HSL → RGB)
const BRAND = {
  primary: [38, 209, 138] as [number, number, number],   // emerald 156° 72% 52%
  primaryDark: [16, 95, 64] as [number, number, number],
  text: [15, 23, 33] as [number, number, number],
  muted: [110, 120, 130] as [number, number, number],
  bgRow: [244, 248, 246] as [number, number, number],
  expense: [240, 92, 76] as [number, number, number],
  income: [38, 209, 138] as [number, number, number],
};

export function exportPDF(items: Transaction[], filename = "khaata-transactions.pdf", rangeLabel?: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const now = new Date();

  // Header band
  doc.setFillColor(...BRAND.primary);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Khaata", 40, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Smart Finance — Transactions Report", 40, 56);
  doc.setFontSize(9);
  doc.text(now.toLocaleString("en-IN"), W - 40, 38, { align: "right" });
  if (rangeLabel) doc.text(rangeLabel, W - 40, 56, { align: "right" });

  // Summary cards
  const totalOut = items.filter(t => t.type !== "income").reduce((s, t) => s + t.amount, 0);
  const totalIn = items.filter(t => t.type === "income").reduce((s, t) => s + t.amount, 0);
  const net = totalIn - totalOut;

  const cardY = 90;
  const cardW = (W - 80 - 20) / 3;
  const cardH = 60;
  const cards = [
    { label: "Spent", value: formatCurrency(totalOut), color: BRAND.expense },
    { label: "Income", value: formatCurrency(totalIn), color: BRAND.income },
    { label: "Net", value: formatCurrency(net), color: net >= 0 ? BRAND.income : BRAND.expense },
  ];
  cards.forEach((c, i) => {
    const x = 40 + i * (cardW + 10);
    doc.setDrawColor(220, 226, 230);
    doc.setFillColor(252, 253, 252);
    doc.roundedRect(x, cardY, cardW, cardH, 6, 6, "FD");
    doc.setTextColor(...BRAND.muted);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(c.label.toUpperCase(), x + 12, cardY + 20);
    doc.setTextColor(...c.color);
    doc.setFontSize(15);
    doc.setFont("helvetica", "bold");
    doc.text(c.value, x + 12, cardY + 44);
  });

  // Table
  autoTable(doc, {
    startY: cardY + cardH + 18,
    head: [["Date", "Type", "Category", "Merchant / Note", "Amount"]],
    body: items.map(t => [
      formatDate(t.date),
      t.type.toUpperCase(),
      t.category,
      t.merchant ? `${t.merchant} — ${t.note}` : t.note,
      `${t.type === "income" ? "+" : "-"} Rs. ${t.amount.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`,
    ]),
    styles: { fontSize: 9, cellPadding: 7, textColor: BRAND.text },
    headStyles: { fillColor: BRAND.primary, textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: BRAND.bgRow },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: 55, fontStyle: "bold" },
      2: { cellWidth: 75 },
      4: { halign: "right", fontStyle: "bold" },
    },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 4) {
        const txt = String(data.cell.raw ?? "");
        if (txt.startsWith("+")) data.cell.styles.textColor = BRAND.income;
        else data.cell.styles.textColor = BRAND.expense;
      }
    },
    didDrawPage: () => {
      const pageH = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(...BRAND.muted);
      doc.text("Generated by Khaata · khaata.app", 40, pageH - 20);
      doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, W - 40, pageH - 20, { align: "right" });
    },
    margin: { left: 40, right: 40 },
  });

  doc.save(filename);
}
